baseURL = "/"
languageCode = "en"
title = "Matthew French"
theme = "basic"

paginate = 5

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

    [[module.mounts]]
      source = "node_modules/lunr/lunr.min.js"
      target = "assets/js/lunr.min.js"

[params]
    author = "Matthew French"
    description = "Matthew French - Digital design, film and photography"
    cloudinary_base_url = "https://res.cloudinary.com/circleseven/image/upload"
    featured_image_list_width = 200
    featured_image_single_width = 400
    featured_image_extension = "jpg"
    post_image_width = 300